export const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRW1pbGUiLCJzdHVkZW50SUQiOiIyMDcyOTEwIiwiaWF0IjoxNjcwMjU2MjE3LCJleHAiOjE2NzI4NDgyMTd9.2J9gA2gNFYxmwQQhAbiWx1BMvsA9OTRZb6lmizAretQ"
export const top10route = "https://quiz-leaderboard-58cf6.nn.r.appspot.com/scores/top10"
